CREATE TABLE EZEN_TABLES (
    TABLE_ID NUMBER(10) PRIMARY KEY,
    TABLE_NAME VARCHAR2(50) NOT NULL UNIQUE,
    STATUS VARCHAR2(20) DEFAULT 'EMPTY' NOT NULL,
    MALE_COUNT NUMBER(3) DEFAULT 0,
    FEMALE_COUNT NUMBER(3) DEFAULT 0,
    TOTAL_AMOUNT NUMBER(10) DEFAULT 0
);

CREATE TABLE EZEN_ORDER_ITEMS(
    ORDER_ITEM_ID NUMBER(10) PRIMARY KEY,
    TABLE_ID NUMBER(10) NOT NULL,
    MENU_NAME VARCHAR2(100) NOT NULL,
    QUANTITY NUMBER(3) NOT NULL,
    PRICE NUMBER(10) NOT NULL,
    CONSTRAINT fk_order_table FOREIGN KEY(TABLE_ID) REFERENCES
    EZEN_TABLES(TABLE_ID) ON DELETE CASCADE   
);

CREATE SEQUENCE order_item_seq START WITH 1 INCREMENT BY 1;

INSERT INTO EZEN_TABLES (TABLE_ID, TABLE_NAME) VALUES (1, 'NO.01');
INSERT INTO EZEN_TABLES (TABLE_ID, TABLE_NAME) VALUES (2, 'NO.02');
INSERT INTO EZEN_TABLES (TABLE_ID, TABLE_NAME) VALUES (3, 'NO.03');
INSERT INTO EZEN_TABLES (TABLE_ID, TABLE_NAME) VALUES (4, 'NO.04');
INSERT INTO EZEN_TABLES (TABLE_ID, TABLE_NAME) VALUES (5, 'NO.05');
INSERT INTO EZEN_TABLES (TABLE_ID, TABLE_NAME) VALUES (6, 'NO.06');

-- 1. 메뉴 정보를 저장할 테이블 생성
CREATE TABLE EZEN_MENUS (
    MENU_ID NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    PRICE NUMBER(10) NOT NULL,
    CATEGORY VARCHAR2(50) NOT NULL,
    IMAGE VARCHAR2(255)
);

-- 2. 메뉴 ID 자동 증가를 위한 시퀀스 생성
CREATE SEQUENCE MENU_SEQ
START WITH 1
INCREMENT BY 1;

-- 3. (중요) 샘플 메뉴 데이터를 1개 이상 추가합니다.
-- 프론트엔드 고객 페이지가 처음 로딩될 때 /api/menus 를 호출하므로,
-- DB에 데이터가 하나도 없으면 빈 배열이 반환됩니다.
INSERT INTO EZEN_MENUS (MENU_ID, NAME, PRICE, CATEGORY, IMAGE) 
VALUES (MENU_SEQ.NEXTVAL, '맥주', 5000, '주류', 'https://placehold.co/150x120/555/fff?text=홍합탕');


//COMMIT;
